### PR TITLE
Make postgres tables statements generator public so it can be used externally too

### PR DESCRIPTION
**Pull request by kedlas**
By using the new public functions, the setup process should be much easier for pgq users.

### CODE REVIEW

**Comment by prochac** [comment]
Until we have Terraform provider ready, and the module isn't marked as stable release, I guess OK.

Maybe keep it in separate package with note, that it may, or may not, be removed later.

```
// Package foo does X, and may, or may not, be removed in a favour of Terraform provide
package foo
```

**Comment by prochac** [comment]
Maybe `x` in a path, to signalize the uncertain future of the package(s)?

https://pkg.go.dev/gotest.tools/x

**Comment by kedlas** [comment]
I vote for having it in `schema` package instead of `x`. I believe this kind of commands will always be there. Even when we create the TF provider (which will solve some of our internal tooling problem) some other users may not use terraform and use something else and we want to offer them the output of these setup functions too.

**Comment by prochac** [comment]
> I vote for having it in `schema` package instead of `x`. I believe this kind of commands will always be there. Even when we create the TF provider (which will solve some of our internal tooling problem) some other users may not use terraform and use something else and we want to offer them the output of these setup functions too.

Well, it's just one SQL query :D 
The Terraform will handle changes between versions, partitioning and much more.
For those who use other approach than Terraform is this not enough. From Go environment you can use go-migrate, goose etc.
This is really handy starting point, but that's it. Nothing more.

**Comment by kedlas** [comment]
Agreed. I move to `x/schema` subdirectory.

**Pull request merged**
